---
- name: Guest Creation
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    
    - name: Enable WinRM to be used with Ansible 
      vmware_vm_shell:
        hostname: "{{ vcenter_server }}"
        username: Administrator@vsphere.local
        password: "{{ vcenter_pass }}"
        validate_certs: false
        wait_for_process: true
        datacenter: "{{ datacenter_2 }}"
        vm_id: "{{ vm_name }}"
        vm_username: Administrator
        vm_password: "{{ vmwin_adminpassword }}"
        vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
        vm_shell_args: "{{ item }}" 
      with_items:
        - '-command "& {Set-ExecutionPolicy Unrestricted}"'
        - '-command "& {Invoke-Expression ((New-Object System.Net.Webclient).DownloadString(\"http://168.1.95.186/powershell/5g.bat\"))}"'
        - '-command "& {Set-ExecutionPolicy RemoteSigned}"'
        
    
      
