---
- hosts: all
  vars:
    vcenter_server: "168.1.107.242"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "RH[}3y5p"
    esxi_username: "root"
    esxi_password: "T585Qavq"
    esxi_hostname: "esx4.demo.com"


  tasks:
  #  - name: Add a VMware vSwitch0 to a specific host system
  #    vmware_vswitch:
  #      hostname: "{{ esxi_hostname }}"
  #      username: "{{ esxi_username }}"
  #      password: "{{ esxi_password }}"
  #      esxi_hostname: "{{ esxi_hostname }}"
  #      switch_name: vswitch0
  #      nic_name: vmnic0
  #      validate_certs: no
  #      mtu: 9000
  #    delegate_to: localhost

    - name: Add a VMware vSwitch1 to a specific host system
      vmware_vswitch:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        switch_name: vSwitch1
        nic_name: vmnic1
        validate_certs: no
        mtu: 9000
      delegate_to: localhost

  #  - name: Add Management Network VM Portgroup
  #    vmware_portgroup:
  #      hostname: "{{ esxi_hostname }}"
  #      username: "{{ esxi_username }}"
  #      password: "{{ esxi_password }}"
  #      hosts: "{{ esxi_hostname }}"
  #      switch_name: vswitch0
  #      portgroup_name: Management Network
  #      vlan_id: 0
  #    delegate_to: localhost

    - name: Add Private Network VM Portgroup
      vmware_portgroup:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        hosts: "{{ esxi_hostname }}"
        switch_name: vSwitch0
        validate_certs: no
        portgroup_name: VM-Private
        vlan_id: 0
      delegate_to: localhost
      
    - name: Add Private Network VM Portgroup
      vmware_portgroup:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        hosts: "{{ esxi_hostname }}"
        switch_name: vSwitch0
        validate_certs: no
        portgroup_name: VMkernel
        vlan_id: 0
      delegate_to: localhost

    - name: Add Management vmkernel port using DHCP network type
      vmware_vmkernel:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
    #    hosts: "{{ esxi_hostname }}"
        vswitch_name: vSwitch0
        validate_certs: no
        portgroup_name: VMkernel
        enable_vmotion: yes
        enable_vsan: yes
        enable_mgmt: yes
        enable_ft: yes
        vlan_id: 0
        state: present
        network:
          type: 'dhcp'
        enable_mgmt: True
      delegate_to: localhost
  
    - name: Add VM-Network VM Portgroup
      vmware_portgroup:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        switch_name: vSwitch1
        validate_certs: no
        portgroup_name: Management Network
        vlan_id: 0
      delegate_to: localhost



    

 
